[package]
name = "garray"
version = "0.1.0"
license = "LGPL-3" # Not LGPL-3-or-later
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glib = { git = "https://github.com/gtk-rs/gtk-rs-core" }
